services:
  zipkin:
    container_name: "zipkin"
    image: "openzipkin/zipkin:2.24"
    ports:
      - 9411:9411

  loki:
    image: grafana/loki:2.7.4
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./tmp/loki:/loki/
      - ./loki-config.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    ports:
      - 9090:9090
    command: [ --config.file=/etc/prometheus/prometheus.yml ]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:9.4.3
    ports:
      - "3000:3000"
    volumes:
      - ./tmp/grafana/:/var/lib/grafana/

  otel-collector:
    container_name: otelcollector
    image: otel/opentelemetry-collector-contrib:0.73.0
    command: [ --config=/etc/otel-collector-config.yml ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - prometheus
      - loki
      - zipkin
    ports:
      #   - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
    #   - 13133:13133 # health_check extension
    #   - 4317:4317 # OTLP gRPC receiver
    #   - 4318:4318 # OTLP http receiver
    #   - 55679:55679 # zpages extension
