scrape_configs:
  # Scrape Prometheus itself every 5 seconds.
  - job_name: "prometheus"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape docker host
  - job_name: "docker_host"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:50501"]
