services:
  keycloak:
    container_name: keycloak-server
    hostname: keycloak-server
    image: "quay.io/keycloak/keycloak:24.0"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin      
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080" # HTTP
     # - "8443:8443" # HTTPS
    volumes:
      - ./.tmp/keycloak/data/import:/opt/keycloak/data/import
    command: ["start-dev"]