services:
  ##### Rabbitmq #####
  rabbitmq:
    image: "rabbitmq:3.11-management"
    container_name: "rabbitmq_server"
    hostname: "rabbitmq_server"
    volumes:
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
      - RABBITMQ_ERLANG_COOKIE=demo_cookie
    ports:
      - 5672:5672
      - 15672:15672

networks:
  default:
    name: rabbit
    driver: bridge
