services:
  ##### Rabbitmq #####
  rabbitmq01:
    image: "rabbitmq:3.11-management"
    container_name: "rabbitmq_server_01"
    hostname: "rabbitmq_server_01"
    volumes:
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./r1/:/config/
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
      - RABBITMQ_ERLANG_COOKIE=demo_cookie
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq.conf
    ports:
      - 5672:5672 # client port
      - 15672:15672 # management ort

  rabbitmq02:
    image: "rabbitmq:3.11-management"
    container_name: "rabbitmq_server_02"
    hostname: "rabbitmq_server_02"
    volumes:
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./r2/:/config/
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
      - RABBITMQ_ERLANG_COOKIE=demo_cookie
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq.conf
    ports:
      - 15673:15672 # management ort

  rabbitmq03:
    image: "rabbitmq:3.11-management"
    container_name: "rabbitmq_server_03"
    hostname: "rabbitmq_server_03"
    volumes:
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./r3/:/config/
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
      - RABBITMQ_ERLANG_COOKIE=demo_cookie
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq.conf
    ports:
      - 15674:15672 # management ort

networks:
  default:
    name: rabbit
    driver: bridge
