services:
  temporal-cli:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 7233:7233 # GRPC Serivce
        - 8233:8233 # UI

networks:
  default:
    name: temporalio-network
    driver: bridge